version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data
        ports:
            - '27017:27017'
    frontend:
        container_name: frontend
        ports:
            - '3000:3000'
        env_file:
            - ./.env
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
